### ISSUE TITLE
Plug twitter API

### ISSUE THREAD

**Issue by dupontbertrand** [Cross-Social-Medias/cross-social-medias#15]
We need to plug the twitter API for search results and more

**Comment by guillaume-gomez** [comment]
https://stackoverflow.com/questions/35879943/twitter-api-authorization-fails-cors-preflight-in-browser

**Comment by guillaume-gomez** [comment]
https://stackoverflow.com/questions/35879943/twitter-api-authorization-fails-cors-preflight-in-browser
